from .classes import Classes
from .allstudentQuestionScore import AllStudentQuestionScore
from .classGradeAnalysis import ClassGradeAnalysis
from .classMistakes import ClassMistakes
from .exam import Exam
from .examPaper import ExamPaper 
from .keyStuAnalysis import KeyStuAnalysis
from .knowledgePoint import KnowledgePoint
from .school import School
from .schoolScoreLine import SchoolScoreLine 
from .scoreD import ScoreD
from .stuAllExamAnalysis import StuAllExamAnalysis 
from .student import Student
from .studentMistakes import StudentMistakes 
from .subjectSelection import SubjectSelection
from .teacher import Teacher
from .user import User
from ._index import db